apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: bigfoot-calculator-web-ingress
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`{{ .Values.ingress.url }}`)
      kind: Rule
      services:
        - name: bigfoot-calculator-web-svc
          port: 80
      middlewares:
        - name: bigfoot-calculator-web-securityheaders
{{ if (eq .Values.traefik.httpsredirect true) }}
        - name: bigfoot-calculator-web-redirectscheme
{{ end }}