apiVersion: v1
appVersion: "1.0"
description: A Helm chart for deploying the Web infrastructure
name: bigfoot-calculator
version: 0.1.1
icon: https://bfcalc.philo.co.nz/favicon.ico
maintainers:
  - name: Morgan Philo
    email: morgan@philo.co.nz